/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

package projeto_final;

import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 837199
 */
public class PrincipalForm extends javax.swing.JInternalFrame {

    /** Creates new form PrincipalForm */
    public PrincipalForm() {
        initComponents();
         this.setTitle("Principal");
        //Para abrir o programa já maximizade usar ExtendedState abaixo
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuItem4 = new javax.swing.JMenuItem();
        areaTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuOpçoes = new javax.swing.JMenu();
        menuDados = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();
        menuMenu = new javax.swing.JMenu();
        menuBebidas = new javax.swing.JMenuItem();
        menuComidas = new javax.swing.JMenuItem();
        menuPagar = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem4.setText("jMenuItem4");

        javax.swing.GroupLayout areaTrabalhoLayout = new javax.swing.GroupLayout(areaTrabalho);
        areaTrabalho.setLayout(areaTrabalhoLayout);
        areaTrabalhoLayout.setHorizontalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );
        areaTrabalhoLayout.setVerticalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        menuOpçoes.setText("Opções");
        menuOpçoes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuOpçoes.setHideActionText(true);

        menuDados.setText("Dados");
        menuDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDadosActionPerformed(evt);
            }
        });
        menuOpçoes.add(menuDados);

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        menuOpçoes.add(menuSair);

        jMenuBar1.add(menuOpçoes);

        menuSobre.setText("Sobre");
        menuSobre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuSobre.setHideActionText(true);
        jMenuBar1.add(menuSobre);

        menuMenu.setText("Menu");
        menuMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menuBebidas.setText("Bebidas");
        menuBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBebidasActionPerformed(evt);
            }
        });
        menuMenu.add(menuBebidas);

        menuComidas.setText("Comidas");
        menuComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuComidasActionPerformed(evt);
            }
        });
        menuMenu.add(menuComidas);

        jMenuBar1.add(menuMenu);

        menuPagar.setText("Pagar");
        menuPagar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuPagar.setHideActionText(true);
        jMenuBar1.add(menuPagar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrabalho, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuDadosActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
            System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBebidasActionPerformed
        abrirFormularioInterno (new BebidasForm());
    }//GEN-LAST:event_menuBebidasActionPerformed

    private void menuComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuComidasActionPerformed
        abrirFormularioInterno (new ComidasForm());
    }//GEN-LAST:event_menuComidasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaTrabalho;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem menuBebidas;
    private javax.swing.JMenuItem menuComidas;
    private javax.swing.JMenuItem menuDados;
    private javax.swing.JMenu menuMenu;
    private javax.swing.JMenu menuOpçoes;
    private javax.swing.JMenu menuPagar;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenu menuSobre;
    // End of variables declaration//GEN-END:variables
    
    private void abrirFormularioInterno (JInternalFrame f) {
        
        if (areaTrabalho.getAllFrames().length ==0){
        areaTrabalho.add(f);
        f.setVisible(true);
        
        //Centralizar o Formulário Interno
        Dimension d = this.getSize();
        f.setLocation(
            (d.width-f.getSize().width)/2,
            (d.height-f.getSize().height)/2);
        } else {
            JOptionPane.showMessageDialog(null,
                    "A aplicação permite apenas uma janela aberta por vez");
        }
    }

    private void setExtendedState(int MAXIMIZED_BOTH) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
