package projeto_finais;

import exemplo07.*;
import java.awt.Dimension;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public LoginForm() {
        
        //Retirar bordas
        //this.setUndecorated(true);
        
        initComponents();
        
        //Propriedades da Janela
        //título da janela
        this.setTitle("Login");
        
        //ajustar tamanho da janela
        this.setResizable(false);
        
        //Centralizar a janela
        this.setLocationRelativeTo(null);
        
        //Propriedades do Botão
        btnEntrar.setToolTipText("Entrar na aplicação");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaTrabalho = new javax.swing.JDesktopPane();
        lblLogin = new javax.swing.JLabel();
        lblEmail1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogin.setFont(new java.awt.Font("Segoe UI", 2, 48)); // NOI18N
        lblLogin.setText("Login");

        lblEmail1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmail1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/8687538_ic_fluent_person_regular_icon (1).png"))); // NOI18N
        lblEmail1.setText("E-mail");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/8687518_ic_fluent_lock_closed_regular_icon.png"))); // NOI18N
        lblSenha.setText("Senha");

        txtSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnEntrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1031506_authorize_enter_login_sign in_signin_icon (1).png"))); // NOI18N
        btnEntrar.setText("   entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        areaTrabalho.setLayer(lblLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        areaTrabalho.setLayer(lblEmail1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        areaTrabalho.setLayer(txtEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        areaTrabalho.setLayer(lblSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        areaTrabalho.setLayer(txtSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        areaTrabalho.setLayer(btnEntrar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout areaTrabalhoLayout = new javax.swing.GroupLayout(areaTrabalho);
        areaTrabalho.setLayout(areaTrabalhoLayout);
        areaTrabalhoLayout.setHorizontalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaTrabalhoLayout.createSequentialGroup()
                .addGroup(areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(areaTrabalhoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(txtEmail)
                            .addComponent(lblLogin, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSenha, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(areaTrabalhoLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnEntrar)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        areaTrabalhoLayout.setVerticalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaTrabalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogin)
                .addGap(65, 65, 65)
                .addComponent(lblEmail1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnEntrar)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrabalho)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        String email =txtEmail.getText();
        String senha = new String(txtSenha.getPassword());
                
        if (email.equals("fulano1@gmail.com") && senha.equals("123456")) {
            JOptionPane.showMessageDialog(null, "Bem vindo ao Sistema");
        } else {
            JOptionPane.showMessageDialog(null, "Usuário/Senha Inválida");
            
            //Limpar os campos do texto
            txtEmail.setText("");
            txtSenha.setText("");
            txtEmail.requestFocus();
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaTrabalho;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
    private void abrirFormularioInterno (JInternalFrame f) {
        
        if (areaTrabalho.getAllFrames().length ==0){
        areaTrabalho.add(f);
        f.setVisible(true);
        
        //Centralizar o Formulário Interno
        Dimension d = this.getSize();
        f.setLocation(
            (d.width-f.getSize().width)/2,
            (d.height-f.getSize().height)/2);
        } else {
            JOptionPane.showMessageDialog(null,
                    "A aplicação permite apenas uma janela aberta por vez");
        }
    } 
}
