/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exemplo08.multiplas_interfaces;

import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 837199
 */
public class PrincipalForm extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalForm
     */
    public PrincipalForm() {
        initComponents();
        
        this.setTitle("Principal");
        //Para abrir o programa já maximizade usar ExtendedState abaixo
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaTrabalho = new javax.swing.JDesktopPane();
        barradeMenu = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuItemSair = new javax.swing.JMenuItem();
        menuLista = new javax.swing.JMenu();
        menuItemSeleçãoSimples = new javax.swing.JMenuItem();
        menuItemSeleçãoMúltipla = new javax.swing.JMenuItem();
        menuTabelas = new javax.swing.JMenu();
        menuItemAdicionar = new javax.swing.JMenuItem();
        menuItemVisualizar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout areaTrabalhoLayout = new javax.swing.GroupLayout(areaTrabalho);
        areaTrabalho.setLayout(areaTrabalhoLayout);
        areaTrabalhoLayout.setHorizontalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
        );
        areaTrabalhoLayout.setVerticalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        menuArquivo.setText("Arquivo");

        menuItemSair.setText("Sair");
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });
        menuArquivo.add(menuItemSair);

        barradeMenu.add(menuArquivo);

        menuLista.setText("Lista");

        menuItemSeleçãoSimples.setText("Seleção Simples (JComboBox)");
        menuItemSeleçãoSimples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSeleçãoSimplesActionPerformed(evt);
            }
        });
        menuLista.add(menuItemSeleçãoSimples);

        menuItemSeleçãoMúltipla.setText("Seleção Múltipla (JList)");
        menuItemSeleçãoMúltipla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSeleçãoMúltiplaActionPerformed(evt);
            }
        });
        menuLista.add(menuItemSeleçãoMúltipla);

        barradeMenu.add(menuLista);

        menuTabelas.setText("Tabelas");

        menuItemAdicionar.setText("Adicionar Item");
        menuItemAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAdicionarActionPerformed(evt);
            }
        });
        menuTabelas.add(menuItemAdicionar);

        menuItemVisualizar.setText("Visualizar");
        menuItemVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVisualizarActionPerformed(evt);
            }
        });
        menuTabelas.add(menuItemVisualizar);

        barradeMenu.add(menuTabelas);

        setJMenuBar(barradeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrabalho, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrabalho, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVisualizarActionPerformed
        abrirFormularioInterno(new TabelaVisualizarForm());
    }//GEN-LAST:event_menuItemVisualizarActionPerformed

    private void menuItemAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAdicionarActionPerformed
        abrirFormularioInterno(new TabelaAdicionarForm());
    }//GEN-LAST:event_menuItemAdicionarActionPerformed

    private void menuItemSeleçãoMúltiplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSeleçãoMúltiplaActionPerformed
        abrirFormularioInterno(new SeleçãoMúltiplaForm());
    }//GEN-LAST:event_menuItemSeleçãoMúltiplaActionPerformed

    private void menuItemSeleçãoSimplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSeleçãoSimplesActionPerformed
        abrirFormularioInterno(new SeleçãoSimplesForm());
    }//GEN-LAST:event_menuItemSeleçãoSimplesActionPerformed

    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaTrabalho;
    private javax.swing.JMenuBar barradeMenu;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuItem menuItemAdicionar;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenuItem menuItemSeleçãoMúltipla;
    private javax.swing.JMenuItem menuItemSeleçãoSimples;
    private javax.swing.JMenuItem menuItemVisualizar;
    private javax.swing.JMenu menuLista;
    private javax.swing.JMenu menuTabelas;
    // End of variables declaration//GEN-END:variables

    private void abrirFormularioInterno (JInternalFrame f) {
        
        if (areaTrabalho.getAllFrames().length ==0){
        areaTrabalho.add(f);
        f.setVisible(true);
        
        //Centralizar o Formulário Interno
        Dimension d = this.getSize();
        f.setLocation(
            (d.width-f.getSize().width)/2,
            (d.height-f.getSize().height)/2);
        } else {
            JOptionPane.showMessageDialog(null,
                    "A aplicação permite apenas uma janela aberta por vez");
        }
    } 
    
    
}
