/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exemplo08;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

public class SelecaoForm extends javax.swing.JFrame {

    public SelecaoForm() {
        initComponents();
        
        this.setTitle("Exemplo");
        this.setResizable(false);
        
        //SELEÇÃO EXCLUSIVA de Radio Button
        ButtonGroup bg = new ButtonGroup();
        bg.add(rdbEngenhariaComputacao);
        bg.add(rdbEngenhariaProducao);
        bg.add(rdbEngenhariaSoftware);
        rdbEngenhariaComputacao.setSelected(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCurso = new javax.swing.JLabel();
        rdbEngenhariaComputacao = new javax.swing.JRadioButton();
        rdbEngenhariaProducao = new javax.swing.JRadioButton();
        rdbEngenhariaSoftware = new javax.swing.JRadioButton();
        lblDisciplinas = new javax.swing.JLabel();
        ckbLaboratorioProgramacaoI = new javax.swing.JCheckBox();
        ckbLaboratorioProgramacaoII = new javax.swing.JCheckBox();
        ckbLaboratorioProgramacaoIII = new javax.swing.JCheckBox();
        ckbLaboratorioProgramacaoIV = new javax.swing.JCheckBox();
        btnVisualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCurso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCurso.setText("Curso");

        rdbEngenhariaComputacao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdbEngenhariaComputacao.setText("Engenharia da Computação");
        rdbEngenhariaComputacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbEngenhariaComputacaoActionPerformed(evt);
            }
        });

        rdbEngenhariaProducao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdbEngenhariaProducao.setText("Engenharia de Produção");
        rdbEngenhariaProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbEngenhariaProducaoActionPerformed(evt);
            }
        });

        rdbEngenhariaSoftware.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdbEngenhariaSoftware.setText("Engenharia de Software");

        lblDisciplinas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDisciplinas.setText("Disciplinas");

        ckbLaboratorioProgramacaoI.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ckbLaboratorioProgramacaoI.setText("Laboratório de Programação I");

        ckbLaboratorioProgramacaoII.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ckbLaboratorioProgramacaoII.setText("Laboratório de Programação II");

        ckbLaboratorioProgramacaoIII.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ckbLaboratorioProgramacaoIII.setText("Laboratório de Programação III");
        ckbLaboratorioProgramacaoIII.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbLaboratorioProgramacaoIIIActionPerformed(evt);
            }
        });

        ckbLaboratorioProgramacaoIV.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ckbLaboratorioProgramacaoIV.setText("Laboratório de Programação IV");

        btnVisualizar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnVisualizar.setText("visualizar");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDisciplinas)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ckbLaboratorioProgramacaoI)
                                .addGap(18, 18, 18)
                                .addComponent(ckbLaboratorioProgramacaoIII))
                            .addComponent(lblCurso)
                            .addComponent(rdbEngenhariaProducao)
                            .addComponent(rdbEngenhariaSoftware)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ckbLaboratorioProgramacaoII)
                                .addGap(18, 18, 18)
                                .addComponent(ckbLaboratorioProgramacaoIV))
                            .addComponent(rdbEngenhariaComputacao)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(btnVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbEngenhariaComputacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbEngenhariaProducao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbEngenhariaSoftware)
                .addGap(38, 38, 38)
                .addComponent(lblDisciplinas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbLaboratorioProgramacaoI)
                    .addComponent(ckbLaboratorioProgramacaoIII))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbLaboratorioProgramacaoII)
                    .addComponent(ckbLaboratorioProgramacaoIV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnVisualizar)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbEngenhariaComputacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbEngenhariaComputacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbEngenhariaComputacaoActionPerformed

    private void rdbEngenhariaProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbEngenhariaProducaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbEngenhariaProducaoActionPerformed

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        
        StringBuilder sb = new StringBuilder();
        sb.append("CURSO").append("\n");
        if (rdbEngenhariaComputacao.isSelected()){
            sb.append(rdbEngenhariaComputacao.getText());
        }else if (rdbEngenhariaProducao.isSelected()){
            sb.append(rdbEngenhariaProducao.getText());
        }else{
            sb.append(rdbEngenhariaSoftware.getText());
        }

        sb.append("\nDISCIPLINAS").append("\n");
        if (ckbLaboratorioProgramacaoI.isSelected()){
            sb.append(ckbLaboratorioProgramacaoI.getText()).append("\n");
        }
        if (ckbLaboratorioProgramacaoII.isSelected()){
            sb.append(ckbLaboratorioProgramacaoII.getText()).append("\n");
        }
        if (ckbLaboratorioProgramacaoII.isSelected()){
            sb.append(ckbLaboratorioProgramacaoIII.getText()).append("\n");
        }
        if (ckbLaboratorioProgramacaoIV.isSelected()){
            sb.append(ckbLaboratorioProgramacaoIV.getText()).append("\n");
        }

        JOptionPane.showMessageDialog(null, sb.toString());
        
        
        
        
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void ckbLaboratorioProgramacaoIIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbLaboratorioProgramacaoIIIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbLaboratorioProgramacaoIIIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecaoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecaoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecaoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecaoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelecaoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JCheckBox ckbLaboratorioProgramacaoI;
    private javax.swing.JCheckBox ckbLaboratorioProgramacaoII;
    private javax.swing.JCheckBox ckbLaboratorioProgramacaoIII;
    private javax.swing.JCheckBox ckbLaboratorioProgramacaoIV;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDisciplinas;
    private javax.swing.JRadioButton rdbEngenhariaComputacao;
    private javax.swing.JRadioButton rdbEngenhariaProducao;
    private javax.swing.JRadioButton rdbEngenhariaSoftware;
    // End of variables declaration//GEN-END:variables
}
