/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package exemplo08;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author 837199
 */
public class SeleçãoSimplesForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public SeleçãoSimplesForm() {
        initComponents();
        
        this.setTitle("Seleção Simples");
        this.setClosable(true);
        this.setMaximizable(true);
        this.setIconifiable(true);
        this.setResizable(false);
        
        //ESPECIFICAR ITENS DO COMBO BOX
        
        cbxDiaSemana.setModel(new DefaultComboBoxModel());
        cbxDiaSemana.addItem("Segunda-Feira");
        cbxDiaSemana.addItem("Terça-Feira");
        cbxDiaSemana.addItem("Quarta-Feira");
        cbxDiaSemana.addItem("Quinta-Feira");
        cbxDiaSemana.addItem("Sexta-Feira");
        cbxDiaSemana.addItem("Sábado");
        cbxDiaSemana.addItem("Domingo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxDiaSemana = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSelecionado = new javax.swing.JTextField();

        cbxDiaSemana.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxDiaSemana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxDiaSemana.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxDiaSemanaItemStateChanged(evt);
            }
        });
        cbxDiaSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDiaSemanaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Dia da Semana");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Item selecionado");

        txtSelecionado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSelecionado.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtSelecionado, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2)))
                    .addComponent(cbxDiaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxDiaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxDiaSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDiaSemanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDiaSemanaActionPerformed

    private void cbxDiaSemanaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxDiaSemanaItemStateChanged
        String item = cbxDiaSemana.getSelectedItem().toString();
        int pos = cbxDiaSemana.getSelectedIndex();
        
        txtSelecionado.setText(item + "(" + pos +")");
    }//GEN-LAST:event_cbxDiaSemanaItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxDiaSemana;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtSelecionado;
    // End of variables declaration//GEN-END:variables
}
