/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exemplo08;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author prodrigo
 */
public class VendasForm extends javax.swing.JFrame {

    public VendasForm() {
        initComponents();
        
        this.setTitle("Vendas");
        this.setResizable(false);
        this.setLocationRelativeTo(null);        
        txtValorFinal.setEnabled(false);
        
        ButtonGroup bg = new ButtonGroup();
        bg.add(rdbDinheiro);
        bg.add(rdbCartaoDebito);
        bg.add(rdbCartaoCredito);
        rdbDinheiro.setSelected(true);
        txtValorVenda.setText("0.00");
    }
    
    private void calcularValorFinal(){
        try {
            double valor = Double.parseDouble(txtValorVenda.getText());
            if (rdbDinheiro.isSelected()){
                valor = valor - (valor*0.05);
            }else if (rdbCartaoDebito.isSelected()){
                valor = valor + (valor*0.05);
            }else{
                valor = valor + (valor*0.10);
            }
            txtValorFinal.setText(String.format("R$ %.2f", valor));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                null, "O valor da venda é inválido.", 
                "Venda", 
                JOptionPane.ERROR_MESSAGE
            );
            txtValorVenda.setText("");
            txtValorFinal.setText("R$ 0,00");
            txtValorVenda.requestFocus();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblValorVenda = new javax.swing.JLabel();
        txtValorVenda = new javax.swing.JTextField();
        pnFormaPagamento = new javax.swing.JPanel();
        rdbDinheiro = new javax.swing.JRadioButton();
        rdbCartaoDebito = new javax.swing.JRadioButton();
        rdbCartaoCredito = new javax.swing.JRadioButton();
        lblValorFinal = new javax.swing.JLabel();
        txtValorFinal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblValorVenda.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblValorVenda.setText("Valor da venda: ");

        txtValorVenda.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtValorVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorVendaKeyReleased(evt);
            }
        });

        pnFormaPagamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Forma de Pagamento"));

        rdbDinheiro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdbDinheiro.setText("Dinheiro");
        rdbDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbDinheiroActionPerformed(evt);
            }
        });

        rdbCartaoDebito.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdbCartaoDebito.setText("Cartão de Débito");
        rdbCartaoDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCartaoDebitoActionPerformed(evt);
            }
        });

        rdbCartaoCredito.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdbCartaoCredito.setText("Cartão de Crédito");
        rdbCartaoCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCartaoCreditoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnFormaPagamentoLayout = new javax.swing.GroupLayout(pnFormaPagamento);
        pnFormaPagamento.setLayout(pnFormaPagamentoLayout);
        pnFormaPagamentoLayout.setHorizontalGroup(
            pnFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFormaPagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbDinheiro)
                    .addComponent(rdbCartaoCredito)
                    .addComponent(rdbCartaoDebito))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnFormaPagamentoLayout.setVerticalGroup(
            pnFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFormaPagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbDinheiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbCartaoDebito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbCartaoCredito)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        lblValorFinal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblValorFinal.setText("Valor final:");

        txtValorFinal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblValorFinal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtValorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnFormaPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblValorVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtValorFinal, txtValorVenda});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorVenda)
                    .addComponent(txtValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorFinal)
                    .addComponent(txtValorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbCartaoDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCartaoDebitoActionPerformed
        calcularValorFinal();
    }//GEN-LAST:event_rdbCartaoDebitoActionPerformed

    private void txtValorVendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorVendaKeyReleased
        calcularValorFinal();
    }//GEN-LAST:event_txtValorVendaKeyReleased

    private void rdbDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbDinheiroActionPerformed
        calcularValorFinal();
    }//GEN-LAST:event_rdbDinheiroActionPerformed

    private void rdbCartaoCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCartaoCreditoActionPerformed
        calcularValorFinal();
    }//GEN-LAST:event_rdbCartaoCreditoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendasForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblValorFinal;
    private javax.swing.JLabel lblValorVenda;
    private javax.swing.JPanel pnFormaPagamento;
    private javax.swing.JRadioButton rdbCartaoCredito;
    private javax.swing.JRadioButton rdbCartaoDebito;
    private javax.swing.JRadioButton rdbDinheiro;
    private javax.swing.JTextField txtValorFinal;
    private javax.swing.JTextField txtValorVenda;
    // End of variables declaration//GEN-END:variables
}
